export default {
    ["mass-delete"]: { "controllers": { "document": { "actions": { "mDelete": true } } } },
    ["default"]: { "controllers": { "collection": { "actions": { "list": true, "getMapping": true, "exists": true, "create": true, "update": true } }, "document": { "actions": { "create": true, "createOrReplace": true, "delete": true, "exists": true, "get": true, "replace": true, "scroll": true, "search": true, "update": true, "upsert": true } }, "index": { "actions": { "list": true, "exists": true } }, "realtime": { "actions": { "count": true, "publish": true, "subscribe": true, "unsubscribe": true } }, "auth": { "actions": { "checkToken": true, "getCurrentUser": true, "getMyRights": true, "logout": true, "updateSelf": true, "createApiKey": true, "deleteApiKey": true } }, "server": { "actions": { "publicApi": true } } } },
    ["user"]: { "controllers": { "collection": { "actions": { "list": true, "getMapping": true } }, "document": { "actions": { "create": true, "createOrReplace": true, "delete": true, "exists": true, "get": true, "replace": true, "scroll": true, "search": true, "update": true, "upsert": true } }, "index": { "actions": { "list": true, "exists": true } }, "realtime": { "actions": { "count": true, "publish": true, "subscribe": true, "unsubscribe": true } }, "auth": { "actions": { "checkToken": true, "getCurrentUser": true, "getMyRights": true, "logout": true, "updateSelf": true } }, "server": { "actions": { "publicApi": true } } } },
    ["mass-create"]: { "controllers": { "document": { "actions": { "mCreate": true } }, "realtime": { "actions": { "publish": true } } } },
    ["mass-get"]: { "controllers": { "document": { "actions": { "mGet": true } } } },
    ["manage-users"]: { "controllers": { "tmc": { "actions": { "createPlayer": true } } } },
    ["mass-update"]: { "controllers": { "document": { "actions": { "mUpdate": true } }, "bulk": { "actions": { "updateByQuery": true } } } }
}
